language: python
python:
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.5-dev
    - 3.6
    - 3.6-dev
    - 3.7-dev
    - nightly
install:
    - pip install -r requirements/production.txt -r requirements/development.txt
    - pip install pytest-cov
    - pip install coveralls
script:
    py.test --cov=dochook tests/
after_success:
    coveralls
