#! /bin/sh
set -eux

export FLASK_ENV=production
export JSONIFY_PRETTYPRINT_REGULAR=False

. .venv/bin/activate
gunicorn dockerhook:app -w 1 -b 127.0.0.1:3000
#gunicorn dockerhook:app -w 1 -b [::1]:3000

