version: 2.1

orbs:
  slack: circleci/slack@4.1.3

jobs:
  build-test-and-notify:
    docker:
      - image: circleci/python:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/circleci-dockerhook
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Configure
          command: |
            mkdir -v      .env
            echo abc123 > .env/DOCKERHOOK_TOKEN
      - run:
          name: Install
          command: |
            sudo addgroup docker
            sudo mkdir -v /etc/sv /var/service
            echo '#! /bin/true' | sudo tee /bin/sv
            sudo chmod -v +x /bin/sv
            sudo ./install.sh
      - run:
          name: Activate
          command: |
            sudo ./activate.sh
      - run:
          name: Uninstall
          command: |
            sudo ./uninstall.sh
#      - run:
#          name: Notify DockerHub
#          command: |
#            curl -X POST "$DOCKERHUB_TRIGGER"
      - slack/status:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  build:
    jobs:
      - build-test-and-notify:
          filters:
            branches:
              ignore: gh-pages
          context: github personal access token

